[chain]
name = "unofficial-102"

[account]
name = "chris"
address = "4036E5F7E6CA0708C4166CFCE9575BD6D4FDC4DC"

[coins]
fermion = 10000
chriscoin = 100000

[[sentry]]
name = "chris"
host = "52.15.176.85"
p2p = 46656

[[validator]]
name = ""
pub_key = ""
power = 1
